# Book settings
title: Professor Brown's Sample Portfolio
author: Sarah M Brown
logo: logo.png


exclude_patterns            : ['data/*',  README.md, template_files/*]  #

# Execution settings
execute:
  allow_errors              : true
